theme: jekyll-theme-minimal
tagline: USA Rail Planner
description: >-
  USA Rail Planner intends to make multi-city trip planning easier.
title: USA Rail Planner
logo: amtrak_header.png
show_downloads: false
app_version: 0.9.5
mac_url: https://nalvarez508.github.io/amtrak-rail-planner/
win_url: https://nalvarez508.github.io/amtrak-rail-planner/